;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		end-of-buffer
		handle-switch-frame
		keyboard-escape-quit
		menu-bar-open
		suspend-frame
		undo-redo
		))

(setq mc/cmds-to-run-once
      '(
		ignore-preserving-kill-region
		lsp-ui-doc--handle-mouse-movement
		))
